// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7yaFry423-IsCUD4SBO1AcWp8v_LXxc',
    appId: '1:30956633829:web:7722ab6b5881408bc2de0c',
    messagingSenderId: '30956633829',
    projectId: 'it-events-1fd80',
    authDomain: 'it-events-1fd80.firebaseapp.com',
    storageBucket: 'it-events-1fd80.appspot.com',
    measurementId: 'G-FBHPM5ZBSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFVr0uJaG_CMuUz0AabwrJAtTEKVTGok',
    appId: '1:30956633829:android:72b3350af6b4cd73c2de0c',
    messagingSenderId: '30956633829',
    projectId: 'it-events-1fd80',
    storageBucket: 'it-events-1fd80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSwxQDG5D6l3hvEL4dGAZsELlcLBV85bY',
    appId: '1:30956633829:ios:0bd89825eedd6d84c2de0c',
    messagingSenderId: '30956633829',
    projectId: 'it-events-1fd80',
    storageBucket: 'it-events-1fd80.appspot.com',
    iosBundleId: 'com.example.ubitevents',
  );
}
